import type { FAQItem, SampleData, PillarConfig, OrderStatus } from "./types";

export const PILLARS: PillarConfig[] = [
  { key: "edukasi", label: "Edukasi Nilai", color: "bg-amber-500", bgColor: "bg-amber-100" },
  { key: "storytelling", label: "Storytelling", color: "bg-indigo-500", bgColor: "bg-indigo-100" },
  { key: "hard-sell", label: "Hard Sell & Promo", color: "bg-emerald-500", bgColor: "bg-emerald-100" },
  { key: "relatable", label: "Relatable Mitos", color: "bg-pink-500", bgColor: "bg-pink-100" },
];

export const STUDIO_PILLARS = [
  "Edukasi Solusi",
  "Storytelling Nyata",
  "Penawaran Spesial",
  "Mitos vs Fakta",
];

export const STATUS_LABELS: Record<OrderStatus, string> = {
  PENDING_PAYMENT: "Menunggu Bayar",
  IN_PROGRESS: "Penyusunan Konten",
  QC_REVIEW: "Kurasi & QC",
  COMPLETED: "Selesai Terkirim",
};

export const STATUS_COLORS: Record<OrderStatus, string> = {
  PENDING_PAYMENT:
    "bg-amber-100 text-amber-800 border border-amber-200",
  IN_PROGRESS:
    "bg-indigo-100 text-indigo-800 border border-indigo-200",
  QC_REVIEW: "bg-pink-100 text-pink-800 border border-pink-200",
  COMPLETED:
    "bg-emerald-100 text-emerald-800 border border-emerald-200",
};

export const KANBAN_COLUMNS: Record<
  OrderStatus,
  { label: string; color: string; textColor: string; bgColor: string }
> = {
  PENDING_PAYMENT: {
    label: "Pending Invoice",
    color: "border-amber-300",
    textColor: "text-amber-700",
    bgColor: "bg-amber-50",
  },
  IN_PROGRESS: {
    label: "Penyusunan Konten",
    color: "border-indigo-300",
    textColor: "text-indigo-700",
    bgColor: "bg-indigo-50",
  },
  QC_REVIEW: {
    label: "Kurasi & QC Final",
    color: "border-pink-300",
    textColor: "text-pink-700",
    bgColor: "bg-pink-50",
  },
  COMPLETED: {
    label: "Terkirim (Done)",
    color: "border-emerald-300",
    textColor: "text-emerald-700",
    bgColor: "bg-emerald-50",
  },
};

export const CATEGORIES = [
  "Kuliner / F&B",
  "Fashion & Apparel",
  "Skincare & Beauty",
  "Jasa Profesional",
  "Gadget / Elektronik",
  "Lainnya",
];

export const TONE_OPTIONS = [
  "Casual Authentic (Storytelling)",
  "Educational & Authoritative",
  "High Conversion Direct-Response",
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    question: "Format berkas apa yang saya terima?",
    answer:
      "Semua deliverables dikirim via Notion workspace yang bisa kamu duplicate, plus file Google Docs untuk backup offline.",
  },
  {
    question: "Apakah saya harus rekam dan edit sendiri?",
    answer:
      "Ya. Karsa menyiapkan naskah, takarir, dan panduan visual. Rekaman dan editing dilakukan oleh tim kamu sendiri atau vendor pilihan.",
  },
  {
    question: "Bagaimana jika ada revisi?",
    answer:
      "Kami menyediakan garansi kalibrasi sudut pesan gratis selama 48 jam setelah deliver. Setelah itu, revisi dikenakan biaya tambahan.",
  },
  {
    question: "Siapa yang memiliki hak cipta konten?",
    answer:
      "100% milik klien. Setelah deliver, semua konten menjadi hak milik penuh brand kamu.",
  },
  {
    question: "Berapa lama waktu pengerjaan?",
      answer:
        "SLA kami adalah 1x24 jam kerja dari brief diterima. Tim kami bekerja cepat tanpa mengorbankan kualitas.",
  },
  {
    question: "Apakah ini langganan?",
    answer:
      "Bukan. Ini pembelian one-time per batch. Tidak ada auto-debit atau komitmen berkelanjutan.",
  },
  {
    question: "Metode pembayaran apa yang diterima?",
    answer:
      "QRIS (semua e-wallet & mobile banking), Virtual Account bank utama (BCA, Mandiri, BRI, BNI).",
  },
];

export const MODULES = [
  {
    number: "01",
    id: "modul-video",
    title: "30 Naskah Video Pendek",
    format: "TikTok, Reels, YouTube Shorts",
    description:
      "Setiap naskah terstruktur dengan Hook 3 detik, Problem Framing, Core Solution, dan CTA yang clear.",
    colSpan: "md:col-span-2",
    icon: "Video",
  },
  {
    number: "02",
    id: "modul-caption",
    title: "30 Takarir AIDA & Riset Tagar",
    format: "120-180 kata/post",
    description:
      "Caption Instagram dengan framework AIDA (Attention-Interest-Desire-Action) lengkap dengan hashtag research.",
    colSpan: "",
    icon: "FileText",
  },
  {
    number: "03",
    id: "modul-seo",
    title: "4 Artikel SEO Website",
    format: "Markdown & Google Docs",
    description:
      "Artikel blog 1.000+ kata dengan H1/H2/H3 terstruktur, meta description, dan keyword optimization.",
    colSpan: "",
    icon: "Globe",
  },
  {
    number: "04",
    id: "modul-radar",
    title: "Audit Celah Kompetitor",
    format: "Positioning Blueprint",
    description:
      "Analisis mendalam celah diferensiasi dari kompetitor utama berdasarkan konten, positioning, dan engagement.",
    colSpan: "",
    icon: "Target",
  },
  {
    number: "05",
    id: "modul-notion",
    title: "Notion Content OS",
    format: "1-Click Duplicate",
    description:
      "Dashboard Notion lengkap untuk mengelola 30 hari konten dengan status tracking dan content calendar.",
    colSpan: "",
    icon: "Layout",
  },
  {
    number: "06",
    id: "modul-broll",
    title: "Panduan Shot List & B-Roll",
    format: "Ramah Pemula Total",
    description:
      "Panduan lengkap pengambilan gambar untuk setiap naskah, termasuk shot composition dan visual references.",
    colSpan: "md:col-span-2",
    icon: "Camera",
  },
];

export const BONUSES = [
  {
    number: "01",
    name: "50 Viral Hook Swipe File Template",
    value: 250000,
    colSpan: "",
  },
  {
    number: "02",
    name: "Panduan Optimasi Bio & Highlight",
    value: 200000,
    colSpan: "",
  },
  {
    number: "03",
    name: "Content Repurposing Framework",
    value: 300000,
    colSpan: "",
  },
  {
    number: "04",
    name: "Garansi Kalibrasi Sudut Pesan 48 Jam",
    value: 350000,
    colSpan: "",
  },
  {
    number: "05",
    name: "Audio Trending & Pacing Blueprint",
    value: 350000,
    colSpan: "sm:col-span-2 lg:col-span-2",
  },
];

export const VALUE_STACK = [
  { item: "30 Naskah Video Pendek", value: 1500000 },
  { item: "30 Takarir AIDA & Riset Tagar", value: 600000 },
  { item: "4 Artikel Blog SEO (1.000 kata)", value: 800000 },
  { item: "Audit Celah 1 Kompetitor Utama", value: 400000 },
  { item: "Notion Dynamic Content OS", value: 300000 },
  { item: "Panduan Shot List B-Roll", value: 250000 },
  { item: "5x Bonus Eksklusif", value: 1450000 },
];

export const SECTORS = [
  {
    name: "F&B, Cafe & Roastery",
    color: "bg-amber-600",
    description: "Sensori rasa, review ASMR & edukasi menu",
  },
  {
    name: "D2C Skincare & Beauty",
    color: "bg-pink-600",
    description: "Ingredient breakdown & myth-busting",
  },
  {
    name: "Fashion & Apparel Lokal",
    color: "bg-indigo-600",
    description: "Styling guide, body fit & detail bahan",
  },
  {
    name: "Jasa Profesional & Edukasi",
    color: "bg-emerald-600",
    description: "Konsultan, klinik, les & agensi mandiri",
  },
];

export const SAMPLE_DATA: Record<string, SampleData[]> = {
  script: [
    {
      title: "F&B Artisan Roastery — Day 04",
      badge: "Sample 1",
      body: `[VISUAL HOOK — 00:00 - 00:03]\nClose-up shot tangan menuangkan kopi hitam ke gelas kristal, background blur café estetik.\n\n[AUDIO/VOICEOVER — 00:03 - 00:10]\n"Tahukah kamu, 70% kopi artisan di Indonesia masih menggunakan metode traditional roasting yang menghasilkan rasa tidak konsisten?"\n\n[VALUE & SOLUTION — 00:10 - 00:20]\nCold Drop Artisan Roastery menggunakan precision roasting technology yang mengontrol temperatur hingga 0.5°C. Setiap biji kopi dipanggang sesuai profil rasa optimalnya. Hasilnya? Crema yang sempurna, aroma yang kompleks, dan rasa yang tidak pernah berubah.\n\n[CALL TO ACTION — 00:20 - 00:25]\n"Ketik 'KOPI' di DM Cold Drop untuk klaim free tasting session batch minggu ini!"`,
    },
    {
      title: "D2C Skincare — Day 09",
      badge: "Sample 2",
      body: `[VISUAL HOOK — 00:00 - 00:03]\nSplit screen: kiri wajah berjerawat, kanan wajah glow-up. Transisi smooth.\n\n[AUDIO/VOICEOVER — 00:03 - 00:10]\n"Myth: Semua serum harus ditumpuk 5 layer supaya kulit glowing. Faktanya? Itu justru bikin skin barrier kamu rusak."\n\n[VALUE & SOLUTION — 00:10 - 00:20]\nLumina Skin Barrier Lab memahami bahwa kulit sehat dimulai dari satu produk yang tepat. Formula barrier-repair kami hanya mengandung 7 ingredients esensial yang terbukti klinis memperkuat skin barrier dalam 14 hari.\n\n[CALL TO ACTION — 00:20 - 00:25]\n"Ketik 'GLOW' di DM Lumina untuk konsultasi skin barrier gratis!"`,
    },
  ],
  caption: [
    {
      title: "F&B — Instagram Caption",
      badge: "Sample 1",
      body: `ATTENTION: Makan pagi tanpa kopi yang bener? Itu kayak main game tanpa save point. 😤\n\nINTEREST: Cold Drop Artisan Roastery hadir dengan single-origin coffee yang di-roast menggunakan precision technology. Setiap tegukan = consistency yang bisa kamu andalkan.\n\nDESIRE: Bayangkan aroma biji kopi yang di-roast sempurna, crema yang tebal, dan rasa yang tidak pernah berubah dari batch pertama hingga terakhir.\n\nACTION: Ketik 'KOPI' di DM kami sekarang! FREE tasting session untuk 20 orang pertama minggu ini. 🎯\n\n#ColdDropCoffee #KopiArtisan #CoffeeLovers #UMKMIndonesia #KontenViral`,
    },
    {
      title: "D2C Skincare — Instagram Caption",
      badge: "Sample 2",
      body: `STOP layering 5 serum! 🚫 Skincare routine kamu malah bikin skin barrier makin rusak.\n\nDi Lumina Skin Barrier Lab, kami percaya: less is more. Satu produk yang tepat > lima produk yang asal comot.\n\nFormula barrier-repair kami hanya 7 ingredients, tapi efeknya? Dokter kulit sendiri yang rekomendasi.\n\n14 hari pakai, kulit terasa beda. Kalau nggak? Garansi uang kembali. 💪\n\nKetik 'GLOW' di DM untuk konsultasi GRATIS! ✨\n\n#LuminaSkin #SkinBarrier #SkincareTips #IndonesiaBeauty`,
    },
  ],
  seo: [
    {
      title: "F&B — SEO Article Outline",
      badge: "Sample 1",
      body: `H1: Panduan Lengkap Memilih Kopi Artisan untuk Pecinta Kopi Pemula\n\nKeyword Focus: kopi artisan indonesia (Volume: 2.400/bulan)\nIntent: Commercial Investigation\n\nH2: Mengapa Kopi Artisan Berbeda dari Kopi Komersial\n- Penjelasan proses artisan roasting\n- Perbedaan rasa yang signifikan\n\nH2: 5 Ciri Kopi Artisan yang Wajib Kamu Ketahui\n- Single origin vs blend\n- Roast profile dan flavor notes\n\nH2: Rekomendasi Roastery Terbaik di Indonesia\n- Cold Drop Artisan Roastery\n- Keunggulan precision roasting\n\nH2: Cara Menyeduh Kopi Artisan di Rumah\n- Grind size, water temperature, brew time\n\nMeta Description: Temukan panduan lengkap memilih kopi artisan terbaik di Indonesia. Pelajari perbedaan, ciri khas, dan rekomendasi roastery berkualitas.`,
    },
    {
      title: "D2C Skincare — SEO Article Outline",
      badge: "Sample 2",
      body: `H1: Mengapa Skin Barrier Kamu Rusak dan Cara Memperbaikinya dengan Tepat\n\nKeyword Focus: skin barrier repair indonesia (Volume: 4.100/bulan)\nIntent: Problem Solving\n\nH2: Apa Itu Skin Barrier dan Mengapa Penting\n- Penjelasan ilmiah tentang stratum corneum\n- Fungsi pelindung kulit\n\nH2: 5 Tanda Skin Barrier Kamu Rusak\n- Kulit kemerahan, sensitif, dehidrasi\n- Reaksi terhadap produk yang biasanya aman\n\nH2: Cara Memperbaiki Skin Barrier dengan Formula yang Tepat\n- Ingredients yang harus dicari\n- Yang harus dihindari\n\nH2: Review Lumina Skin Barrier Lab\n- Formula 7 ingredients essential\n- Hasil klinis 14 hari\n\nMeta Description: Kenali tanda rusaknya skin barrier dan temukan cara memperbaikinya dengan formula barrier-repair yang terbukti klinis.`,
    },
  ],
};

export const PROBLEMS = [
  {
    number: "01",
    title: "Creative Burnout",
    description:
      "Habis ide setelah 3 hari posting. Stuck di caption yang itu-itu aja.",
  },
  {
    number: "02",
    title: "Biaya Agensi Membengkak",
    description:
      "Bayar Rp1.5 juta per batch konten. Belum termasuk revisi yang dikenakan biaya tambahan.",
  },
  {
    number: "03",
    title: "Konten Tanpa Niat Beli",
    description:
      "Banyak likes, tapi tidak ada yang DM atau beli. Engagement ≠ konversi.",
  },
];

export const SEED_ORDERS = [
  {
    order_id: "INV-993810",
    brand: "Aroma Sambal Tempong Ibu Sri",
    category: "Kuliner / F&B",
    competitor: "@sambal_bu_rudy",
    description: "Sambal tempong pedas khas Jawa Timur dengan cita rasa autentik dan kemasan modern.",
    email: "ibusrisambal@gmail.com",
    phone: "081234567890",
    status: "IN_PROGRESS" as const,
    hours_offset: -2,
  },
  {
    order_id: "INV-982104",
    brand: "Lumina Skin Barrier Lab",
    category: "Skincare & Beauty",
    competitor: "@somethincofficial",
    description: "Skincare barrier-repair dengan 7 ingredients essential, diformulasikan untuk kulit sensitif Indonesia.",
    email: "lumina.skincare@gmail.com",
    phone: "081234567891",
    status: "IN_PROGRESS" as const,
    hours_offset: -5,
  },
  {
    order_id: "INV-971482",
    brand: "Karsa Modular Studio",
    category: "Fashion & Apparel",
    competitor: "@dekoruma",
    description: "Furniture modular custom untuk apartemen urban dengan desain scandinavian minimalis.",
    email: "karsa.modular@gmail.com",
    phone: "081234567892",
    status: "IN_PROGRESS" as const,
    hours_offset: -7,
  },
  {
    order_id: "INV-960291",
    brand: "PajakMudah Konsultan UMKM",
    category: "Jasa Profesional",
    competitor: "@klikpajak",
    description: "Konsultan pajak UMKM dengan layanan konsultasi online dan pelaporan SPT tahunan.",
    email: "pajakmudah@gmail.com",
    phone: "081234567893",
    status: "IN_PROGRESS" as const,
    hours_offset: -11,
  },
  {
    order_id: "INV-952819",
    brand: "Cold Drop Artisan Roastery",
    category: "Kuliner / F&B",
    competitor: "@kopikenangan.id",
    description: "Artisan coffee roastery dengan precision roasting technology dan single-origin beans.",
    email: "coldbrew.drop@gmail.com",
    phone: "081234567894",
    status: "QC_REVIEW" as const,
    hours_offset: -16,
    notion_url: "https://notion.so/workspace/cold-drop",
  },
  {
    order_id: "INV-941092",
    brand: "FitDaily Meal Prep Diet",
    category: "Kuliner / F&B",
    competitor: "@yellowfitkitchen",
    description: "Meal prep sehat dengan kalori terkontrol, dikirim segar setiap minggu ke Jabodetabek.",
    email: "fitdaily.meal@gmail.com",
    phone: "081234567895",
    status: "QC_REVIEW" as const,
    hours_offset: -19,
    notion_url: "https://notion.so/workspace/fitdaily",
  },
  {
    order_id: "INV-930419",
    brand: "Zenith Gadget Armor",
    category: "Gadget / Elektronik",
    competitor: "@spigen_id",
    description: "Casing dan pelindung gadget premium dengan material military-grade dan desain tipis.",
    email: "zenith.gadget@gmail.com",
    phone: "081234567896",
    status: "PENDING_PAYMENT" as const,
    hours_offset: -1,
  },
  {
    order_id: "INV-920188",
    brand: "Nala Baby Organic Wear",
    category: "Fashion & Apparel",
    competitor: "@littlepalmerhaus",
    description: "Pakaian bayi organik dengan sertifikasi GOTS, aman untuk kulit sensitif newborn.",
    email: "nala.baby@gmail.com",
    phone: "081234567897",
    status: "PENDING_PAYMENT" as const,
    hours_offset: -3,
  },
  {
    order_id: "INV-881920",
    brand: "Bakso Goreng Anugerah",
    category: "Kuliner / F&B",
    competitor: "@baksogorenggajah",
    description: "Bakso goreng renyah dengan isian daging sapi pilihan, franchise nasional.",
    email: "bakso.goreng@gmail.com",
    phone: "081234567898",
    status: "COMPLETED" as const,
    hours_offset: -48,
    notion_url: "https://notion.so/workspace/bakso-anugerah",
  },
  {
    order_id: "INV-873910",
    brand: "Sora Japanese Hair Studio",
    category: "Jasa Profesional",
    competitor: "@onepiecehair",
    description: "Salon Jepang premium dengan teknologi perawatan rambut terbaru dan stylist bersertifikat.",
    email: "sora.hair@gmail.com",
    phone: "081234567899",
    status: "COMPLETED" as const,
    hours_offset: -72,
    notion_url: "https://notion.so/workspace/sora-hair",
  },
  {
    order_id: "INV-864019",
    brand: "Aethel Linen & Cotton Wear",
    category: "Fashion & Apparel",
    competitor: "@cottonink",
    description: "Pakaian linen dan katun premium untuk pria modern dengan desain timeless.",
    email: "aethel.wear@gmail.com",
    phone: "081234567900",
    status: "COMPLETED" as const,
    hours_offset: -96,
    notion_url: "https://notion.so/workspace/aethel",
  },
  {
    order_id: "INV-852918",
    brand: "Veloce Auto Detailing",
    category: "Jasa Profesional",
    competitor: "@scuto.id",
    description: "Auto detailing premium dengan nano-ceramic coating dan paint protection film.",
    email: "veloce.detail@gmail.com",
    phone: "081234567901",
    status: "COMPLETED" as const,
    hours_offset: -120,
    notion_url: "https://notion.so/workspace/veloce",
  },
  {
    order_id: "INV-841098",
    brand: "Glow Botanic Herbal Soap",
    category: "Skincare & Beauty",
    competitor: "@sensatia_botanicals",
    description: "Sabun herbal handmade dengan bahan organik, ramah lingkungan dan kulit sensitif.",
    email: "glow.botanic@gmail.com",
    phone: "081234567902",
    status: "COMPLETED" as const,
    hours_offset: -144,
    notion_url: "https://notion.so/workspace/glow-botanic",
  },
  {
    order_id: "INV-830291",
    brand: "Kopi Susu Tetangga Senja",
    category: "Kuliner / F&B",
    competitor: "@kopituku",
    description: "Kopi susu kekinian dengan resep turun-temurun dan harga terjangkau untuk anak muda.",
    email: "tetangga.senja@gmail.com",
    phone: "081234567903",
    status: "COMPLETED" as const,
    hours_offset: -168,
    notion_url: "https://notion.so/workspace/tetangga-senja",
  },
  {
    order_id: "INV-821948",
    brand: "Urban Leather Craft",
    category: "Fashion & Apparel",
    competitor: "@revoltindustry",
    description: "Aksesoris kulit handmade premium untuk pria dan wanita urban.",
    email: "urban.leather@gmail.com",
    phone: "081234567904",
    status: "COMPLETED" as const,
    hours_offset: -192,
    notion_url: "https://notion.so/workspace/urban-leather",
  },
  {
    order_id: "INV-810482",
    brand: "Dentika Dental Clinic",
    category: "Jasa Profesional",
    competitor: "@farsdent",
    description: "Klinik gigi modern dengan teknologi digital dentistry dan layanan estetik gigi.",
    email: "dentika.clinic@gmail.com",
    phone: "081234567905",
    status: "COMPLETED" as const,
    hours_offset: -216,
    notion_url: "https://notion.so/workspace/dentika",
  },
  {
    order_id: "INV-799102",
    brand: "Kyoto Matcha Bar Tangerang",
    category: "Kuliner / F&B",
    competitor: "@matchabae",
    description: "Matcha bar autentik Jepang dengan ceremonial grade matcha dan dessert fusion.",
    email: "kyoto.matcha@gmail.com",
    phone: "081234567906",
    status: "COMPLETED" as const,
    hours_offset: -264,
    notion_url: "https://notion.so/workspace/kyoto-matcha",
  },
  {
    order_id: "INV-788291",
    brand: "ErgoDesk Indonesia",
    category: "Gadget / Elektronik",
    competitor: "@oxihom",
    description: "Meja kerja ergonomis standing desk dengan motor elektrik dan integrated cable management.",
    email: "ergodesk.id@gmail.com",
    phone: "081234567907",
    status: "COMPLETED" as const,
    hours_offset: -288,
    notion_url: "https://notion.so/workspace/ergodesk",
  },
  {
    order_id: "INV-777102",
    brand: "Seroja Hijab Syar'i",
    category: "Fashion & Apparel",
    competitor: "@kamiidea",
    description: "Hijab syar'i premium dengan bahan premium dan desain elegan untuk muslimah modern.",
    email: "seroja.hijab@gmail.com",
    phone: "081234567908",
    status: "COMPLETED" as const,
    hours_offset: -336,
    notion_url: "https://notion.so/workspace/seroja",
  },
  {
    order_id: "INV-766190",
    brand: "PureWater RO Filter Rumahan",
    category: "Lainnya",
    competitor: "@coway_id",
    description: "Sistem filter air RO untuk rumah tangga dengan teknologi 5 tahap penyaringan.",
    email: "purewater.ro@gmail.com",
    phone: "081234567909",
    status: "COMPLETED" as const,
    hours_offset: -360,
    notion_url: "https://notion.so/workspace/purewater",
  },
  {
    order_id: "INV-755481",
    brand: "Roti Sisir Mentega Surabaya",
    category: "Kuliner / F&B",
    competitor: "@roti_matahari",
    description: "Roti sisir mentega khas Surabaya dengan resep turun-temurun dan topping kekinian.",
    email: "roti.sisir@gmail.com",
    phone: "081234567910",
    status: "COMPLETED" as const,
    hours_offset: -408,
    notion_url: "https://notion.so/workspace/roti-sisir",
  },
  {
    order_id: "INV-744019",
    brand: "Kalyana Yoga & Pilates",
    category: "Jasa Profesional",
    competitor: "@celebrityfitness",
    description: "Studio yoga dan pilates premium dengan instruktur bersertifikat internasional.",
    email: "kalyana.yoga@gmail.com",
    phone: "081234567911",
    status: "COMPLETED" as const,
    hours_offset: -432,
    notion_url: "https://notion.so/workspace/kalyana",
  },
  {
    order_id: "INV-733910",
    brand: "Nusantara Heritage Batik Pria",
    category: "Fashion & Apparel",
    competitor: "@danarhadi",
    description: "Batik pria premium dengan motif tradisional yang diinterpretasikan dalam desain kontemporer.",
    email: "heritage.batik@gmail.com",
    phone: "081234567912",
    status: "COMPLETED" as const,
    hours_offset: -456,
    notion_url: "https://notion.so/workspace/heritage-batik",
  },
  {
    order_id: "INV-722109",
    brand: "DermaCleanse Micellar Water",
    category: "Skincare & Beauty",
    competitor: "@garnierindonesia",
    description: "Micellar water gentle cleanser untuk kulit sensitif Indonesia dengan ekstrak aloe vera.",
    email: "dermacleanse@gmail.com",
    phone: "081234567913",
    status: "COMPLETED" as const,
    hours_offset: -504,
    notion_url: "https://notion.so/workspace/dermacleanse",
  },
  {
    order_id: "INV-711902",
    brand: "PawPal Pet Care & Grooming",
    category: "Jasa Profesional",
    competitor: "@petkingdom",
    description: "Layanan grooming hewan peliharaan premium dengan home service dan perawatan holistic.",
    email: "pawpal.pet@gmail.com",
    phone: "081234567914",
    status: "COMPLETED" as const,
    hours_offset: -528,
    notion_url: "https://notion.so/workspace/pawpal",
  },
  {
    order_id: "INV-700291",
    brand: "SnackSehat Keripik Jamur Tiram",
    category: "Kuliner / F&B",
    competitor: "@kriuk_id",
    description: "Keripik jamur tiram sehat tanpa MSG, diproses dengan teknologi vacuum frying.",
    email: "snacksehat@gmail.com",
    phone: "081234567915",
    status: "COMPLETED" as const,
    hours_offset: -576,
    notion_url: "https://notion.so/workspace/snacksehat",
  },
  {
    order_id: "INV-699102",
    brand: "AeroFit Activewear Gym",
    category: "Fashion & Apparel",
    competitor: "@gymshark",
    description: "Activewear gym premium dengan material moisture-wicking dan desain yang memotivasi.",
    email: "aerofit.wear@gmail.com",
    phone: "081234567916",
    status: "COMPLETED" as const,
    hours_offset: -600,
    notion_url: "https://notion.so/workspace/aerofit",
  },
  {
    order_id: "INV-688190",
    brand: "Solusi Akun Kursus Mandarin",
    category: "Jasa Profesional",
    competitor: "@cakap_id",
    description: "Kursus Mandarin online dengan native speaker dan kurikulum HSK terstruktur.",
    email: "solusi.mandarin@gmail.com",
    phone: "081234567917",
    status: "COMPLETED" as const,
    hours_offset: -624,
    notion_url: "https://notion.so/workspace/mandarin",
  },
  {
    order_id: "INV-677019",
    brand: "Dapur Brownies Fudgy Lumer",
    category: "Kuliner / F&B",
    competitor: "@fudgybro",
    description: "Brownies fudgy premium dengan topping premium dan pengiriman same-day Jabodetabek.",
    email: "dapur.brownies@gmail.com",
    phone: "081234567918",
    status: "COMPLETED" as const,
    hours_offset: -648,
    notion_url: "https://notion.so/workspace/brownies",
  },
  {
    order_id: "INV-666192",
    brand: "SoundWave TWS Bluetooth Earbuds",
    category: "Gadget / Elektronik",
    competitor: "@soundcore_id",
    description: "TWS earbuds dengan active noise cancellation dan battery life 36 jam total.",
    email: "soundwave.tws@gmail.com",
    phone: "081234567919",
    status: "COMPLETED" as const,
    hours_offset: -672,
    notion_url: "https://notion.so/workspace/soundwave",
  },
  {
    order_id: "INV-655102",
    brand: "Koleksi Sandal Kulit Pria Java",
    category: "Fashion & Apparel",
    competitor: "@portblue",
    description: "Sandal kulit handmade pria dengan desain casual premium dan comfort insole.",
    email: "java.sandal@gmail.com",
    phone: "081234567920",
    status: "COMPLETED" as const,
    hours_offset: -672,
    notion_url: "https://notion.so/workspace/java-sandal",
  },
  {
    order_id: "INV-644190",
    brand: "Camilan Keripik Tempe Mendoan Oven",
    category: "Kuliner / F&B",
    competitor: "@tempe_crispy",
    description: "Keripik tempe mendoan panggang oven dengan rasa rempah tradisional dan tekstur renyah.",
    email: "tempe.mendoan@gmail.com",
    phone: "081234567921",
    status: "COMPLETED" as const,
    hours_offset: -696,
    notion_url: "https://notion.so/workspace/tempe-mendoan",
  },
  {
    order_id: "INV-633019",
    brand: "Optik Mata Sehat Express",
    category: "Jasa Profesional",
    competitor: "@optik_seis",
    description: "Optik modern dengan layanan pemeriksaan mata cepat dan kacamata ready-stock.",
    email: "mata.sehat@gmail.com",
    phone: "081234567922",
    status: "COMPLETED" as const,
    hours_offset: -696,
    notion_url: "https://notion.so/workspace/optik-sehat",
  },
  {
    order_id: "INV-622108",
    brand: "Dapur Sambal Bawang Bu Broto",
    category: "Kuliner / F&B",
    competitor: "@sambal_bu_rudy",
    description: "Sambal bawang pedas khas Jogja dengan resep warisan turun-temurun dan kemasan higienis.",
    email: "sambal.broto@gmail.com",
    phone: "081234567923",
    status: "COMPLETED" as const,
    hours_offset: -720,
    notion_url: "https://notion.so/workspace/sambal-broto",
  },
];
